### PR TITLE
fix display of submission graded, not released (iss. #1208)

### LINKED ISSUE #1208: update job must pull null-grade submissions
(cron job needs to pull in submissions with null grade, if the submission has been graded but grades are not released)

### Expected behavior (A description of what you expected to happen) : 

Instructors may grade on assignment submissions, but wait till later date to release those grades.

### Describe the bug (Tell us what happens instead of the expected behavior) :

Currently, MyLA cron job does not pull in those "graded but grades are not released yet" submissions

### Steps to Reproduce :
1. Before submitting to an assignment, student will see this assignment marked as "unsubmitted" in Assignment Planning view
2. Student submit an assignment
3. After MyLA cron job, student can view the assignment as "submitted but not graded"
4. Instructor graded the submission without releasing it
5. After another MyLA cron job, student now see the assignment as "unsubmitted" again.

### PR DESCRIPTION
**Pull request by zqian**
Fixes #1208.

### CODE REVIEW

**Review by lsloan — APPROVED** [review]
If this is giving the results we need, then I guess it's good.  The queries were tricky to follow.  From a maintenance perspective, both for developers and code reviewers, it would be helpful if the queries didn't need to be compressed into one line each.  Better formatting would help.

**Comment by lsloan** [comment]
Although I approved this a couple hours ago, I was still thinking about this because I wanted to understand it better.  I corrected the name of the variable, because I see it doesn't have anything to do with URLs at all.

I'm not sure whether the failing check is significant.  I remember this problem being flagged in other projects, like course-inventory.

Note that this PR has conflicts.  Be sure to resolve those before merging.

**Comment by zqian** [comment]
Thanks for the reviews and variable name change. 

I will not fix the alerted "SQL Injection Attack" error since it is not introduced by this PR. I have also fixed the merge conflict.

**Comment by lsloan** [comment]
> I will not fix the alerted "SQL Injection Attack" error since it is not introduced by this PR.

In this case, a fix for that might be more than trivial, and working on it could make us miss the chance to deploy before the production freeze starts.

I'll point out that my fellow developers wouldn't accept my "problem not introduced here" reasoning in the past.  I had to resolve problems at the time regardless, but it wasn't such a tight deadline.

**Pull request merged**
