### PR TITLE
Fixes #1293 - Webpack doesn't seem to be reloading the frontend

### LINKED ISSUE #1293: Webpack doesn't seem to be live reloading the frontend anymore on OSX with certain options
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
When developing and changing the code we used to see changes in the frontend rebuilding. This is the point of webpack_watcher. However it doesn't look like this happens in OSX Docker if you have the option Use gRPC FUSE unchecked.

Unchecking this can give a disk performance boost when developing. 

### Describe the bug (Tell us what happens instead of the expected behavior) :
It seems like the fix for this is to both switch the watchOptions poll to true and also switch `delegated` to `cached` for the mount options.

Note the `delegated` and `cached` are not used on Windows and don't appear to be used in OSX if the Docker option _"Use gRPC FUSE for file sharing"_ is checked.

### Steps to Reproduce :
1. On OSX Docker General have the option Use "gRPC FUSE" unchecked and Apply/Restart.
2. Start up MyLA for development
2. Modify some frontend javascript code
3. The changes should be updated. If you look at the `docker logs webpack_watcher` it should also show changes compiled.

This will only affect development

### PR DESCRIPTION
**Pull request by jonespm**
Is anyone else on any platform seeing this issue? 

Maybe it's just because I have "Use gRPC FUSE" unchecked? I'll try to restart with that checked.

Okay it's only seems like this is an issue if that option is unchecked.

### CODE REVIEW

**Comment by jonespm** [comment]
Some of these ideas seemed to be included in #996 but that wasn't ever merged.

**Comment by ssciolla** [comment]
@jonespm, why is this necessary if you just needed to check the "Use gRPC FUSE for file sharing" option? Is that not something we should be doing?

Maybe these changes are good for other reasons, but if the option change is all that's needed to fix `webpack`, I'm thinking this PR and the issue should be renamed.

**Comment by jonespm** [comment]
I'd mentioned in the ticket that unchecking this option gets the builds and startup to go about twice as fast. It seems like there's still a performance issue with Docker on OSX and at least going back with these options fixes it. 

I'm also not 100% sure if this is an issue with Windows or not. I was hearing from Daniel Zhang that his webpack wasn't reloading on Windows in the Canvas App Explorer project. It might just be related to the watch options there, as I'm seeing these volume options are only applicable to OSX without gRPC.

**Comment by pushyamig** [comment]
@jonespm I think in past i had problem when `Use gRPC FUSE` was checked, but not anymore(maybe after upgrade of Docker version). Now I have that checked and I didn't even applied changes from this PR and I can see webpack is creating a new `main-xx.js` bundle each time.

I will approve this request since this is fixing problem on Windows and is working for Mac.

**Review by pushyamig — APPROVED** [review]

**Comment by jonespm** [comment]
Thanks! I was going to do a small fix and ensure the watchOptions was only set when development was enabled. I'm not **entirely** sure why I even had to add that to get it working either. 

Is it already setting watch: true in dev and watch: false in prod? Then I guess it's all set as watchOptions don't matter if it's false. 

https://webpack.js.org/configuration/watch/

**Comment by jonespm** [comment]
Okay looks like the webpack_watcher container locally is running watch explicitly. So this should be fine. Thanks for checking!

**Pull request merged**
