### PR TITLE
Fixes #739 - Login and Logout redirect URL's are documented incorrectly

### LINKED ISSUE #739: Login and Logout redirect URL's are documented incorrectly
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
LOGIN_REDIRECT_URL and LOGOUT_REDIRECT_URL are actually DJANGO_LOGIN_REDIRECT_URL and DJANGO_LOGOUT_REDIRECT_URL in the code. Need to update the documentation to match.

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
These *actually* should be called "SAML_LOGOUT_REDIRECT_URL" 

Maybe we should just leave them as LOGOUT_REDIRECT_URL / LOGIN_REDIRECT_URL and fix it in the code?

**Comment by pushyamig** [comment]
I agree having a prefix as SAML make more sense, let's do it the right way.

**Comment by jonespm** [comment]
Maybe this would be too big of a change. Now that we have JSON for config I was thinking we could group all the SAML stuff together.

```
  "SAML": {
    "URL_BASE": "/accounts",
    "DEFAULT_IDP": "",
    "FILES_BASE": "/saml/",
    "METADATA_FILE": "/file/path/metadata.xml",
    "PEM_FILE": "/file/path/file.pem",
    "ACS_DEFAULT_REDIRECT": "/",
    "LOGIN_REDIRECT_URL": "/",
    "LOGOUT_REDIRECT_URL": "/",
    "ATTRIBUTE_MAPPING": {
      "uid": [
        "username"
      ],
      "mail": [
        "email"
      ],
      "givenName": [
        "first_name"
      ],
      "sn": [
        "last_name"
      ]
    }
  }
```

**Comment by pushyamig** [comment]
Agreed

**Pull request merged**
