### PR TITLE
Added function annotations for return types and parameter types (#301) 

### PR DESCRIPTION
**Pull request by luctiger98**
My partner @jacobmal and I have added function annotations for return types and parameter types for the following Python dashboard files: admin.py, context_processors.py, models.py, and views.py.

Function annotations adhere to the PEP 3107 style guidelines found here: https://www.python.org/dev/peps/pep-3107/

In order to accommodate for certain parameter types and returning multiple types, the following code was placed at the top of these files when necessary:

from typing import Union
from django.http import HttpRequest, HttpResponse, JsonResponse

### CODE REVIEW

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 14
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/student-dashboard-django/student-dashboard-django/pullRequest?prid=4611099&bid=15469442)

**Comment by luctiger98** [comment]
I have tested my build and MyLA seems to run correctly. Additionally, when looking at the Codacy/PR Quality Review details, only a few specific functions are pinged as "bad," despite me utilizing the same styling for every function. Why might this be the case?

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 14
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/ITS_Teaching_And_Learning/student-dashboard-django/pullRequest?prid=4611099&bid=15469442)

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 14
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/ITS_Teaching_And_Learning/student-dashboard-django/pullRequest?prid=4611099&bid=15469442)

**Comment by zqian** [comment]
This PR has been applied as a new PR:  https://github.com/tl-its-umich-edu/my-learning-analytics/pull/840/commits 

I will close this PR and track status over there. Thanks for your contribution, @luctiger98!

**Pull request closed without merging**
