### PR TITLE
Fixes #1129 - Split out pip install from apt-get step in Dockerfile

### LINKED ISSUE #1129: Split out pip install from apt-get step in Dockerfile
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Describe the bug (Tell us what happens instead of the expected behavior) :
We should split out the pip install from the RUN line in the docker file that installs OS dependencies. This step takes almost 4 minutes for each step and really slows down development when just changing and testing requirements.

I think we also could add a little more cleanup in here to reduce image size.

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
Leaning up /var/lib/apt/lists only saves about 17M but it's not necessary. Also the --no-cache-dir option reduces the image size. I'll get some numbers here. Though this change is mostly to split out the pip so it doesn't have to rebuild the apt-get layer on changes.

**Comment by jonespm** [comment]
The image goes from 1.16GB to 986MB.

**Comment by zqian** [comment]
It is a good practice to separate out the pip install statement. However, I did not see much performance improvement. This is what I have tested:

Without the PR:

docker-compose down
docker-compose build
change the requirements.txt -pandas==1.0.5 +pandas==1.1.4
docker-compose build
Here is the step with "apt-get" and "pip install" COMBINED:
=> [app 4/11] RUN apt-get update && apt-get install -y --no-install-recommends build-essential default-libmysqlclient-dev libpq-dev netcat vim-tiny jq python3-dev 163.7s

With the PR:

docker-compose down
docker-compose build
change the requirements.txt -pandas==1.0.5 +pandas==1.1.4
docker-compose build
Here is the step with "apt-get" and "pip install" SEPARATED:

=> [app 4/12] RUN apt-get update && apt-get install -y --no-install-recommends build-essential default-libmysqlclient-dev libpq-dev netcat vim-tiny jq python3-dev 69.1s
=> [app 5/12] RUN pip install --no-cache-dir -r requirements.txt 105.8s

Those two steps took about the same amount of time compared to the prior PR code.

**Comment by zqian** [comment]
Verified the image size reduction with "docker image ls":

Prior to the PR:

REPOSITORY                              TAG                 IMAGE ID            CREATED              SIZE
my-learning-analytics_web               latest              51ca6dac0656        About a minute ago   1GB
my-learning-analytics_webpack_watcher   latest              e9885f320128        10 minutes ago       419MB

After the PR:

REPOSITORY                              TAG                 IMAGE ID            CREATED              SIZE
my-learning-analytics_web               latest              799f06c319dd        About a minute ago   971MB
my-learning-analytics_webpack_watcher   latest              e91cb86e165b        9 minutes ago        419MB

**Review by zqian — APPROVED** [review]

**Pull request merged**
