### PR TITLE
Fixes #1484 - MyLA importing incorrect timezone times

### LINKED ISSUE #1432: May need to make America/Detroit in cron config configurable
Noticed this when I was reviewing the cron updates. I'm not sure if this is the same for other schools that might be hosted but this value that's used in the cron config should _probably_ come from the django.conf `settings.TIME_ZONE` or a probably a new value to indicate the time zone in the database? There's 2 usages of this. 

This looks like it was in the previous UDW config so it may not be an issue, or it might just not be one reported yet. 

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/2fc6c4e804aab4ed56e37f411b32d275561c5c9f/config/cron_udp.hjson#L246

### LINKED ISSUE #1484: MyLA importing incorrect timezone times
### Expected behavior (A description of what you expected to happen) : 

Timestamps for locally computed times, such as the `grade_posted_local_date` field in the `submission` table, to have the correctly computed time for the `America/Detroit` configured timezone.

### Describe the bug (Tell us what happens instead of the expected behavior) :

Timestamps are showing as 4 hours ahead of UTC instead of 5 hours behind for the correct `America/Detroit` (`EST`) time.

### Steps to Reproduce :

1. Select an assignment from the MyLA database:
    ```sql
    SELECT id FROM assignment ORDER BY due_date DESC LIMIT 1;
    ```
    Response:
    ```
    -- response --
    +-----------------+
    | id              |
    +-----------------+
    | 420000011111111 |
    +-----------------+
    ```
2. Select a user of the assignment:
    ```sql
    SELECT
        assignment_id,
        user_id,
        grade_posted_local_date
    FROM submission
    WHERE assignment_id = 420000011111111
        AND user_id = 420000002222222;
    ```
    Response:
    ```
    +-----------------+-----------------+----------------------------+
    | assignment_id   | user_id         | grade_posted_local_date    |
    +-----------------+-----------------+----------------------------+
    | 420000011111111 | 420000002222222 | 2021-10-17 20:49:11.908000 |
    +-----------------+-----------------+----------------------------+
    ```
    This provides the following information:
    - long user id: `420000002222222`
    - short user id: `2222222` (dropping the `42000000` prefix)
    - assignment id: `420000011111111`

> The rest of the queries below are against one of the Unizin host UDP `context_store`.

3. Fetch the `learner_activity_result_id` for the assignment:
    ```sql
    SELECT
        entity.learner_activity_result.learner_activity_result_id,
        keymap.learner_activity.lms_int_id,
        keymap.person.lms_ext_id
    FROM entity.learner_activity_result
    LEFT JOIN keymap.person ON keymap.person.id = entity.learner_activity_result.person_id
    LEFT JOIN keymap.learner_activity ON keymap.learner_activity.id = entity.learner_activity_result.learner_activity_id
    WHERE cast(keymap.person.lms_ext_id AS bigint) = 2222222                      -- short user id
        AND cast(keymap.learner_activity.lms_int_id AS BIGINT) = 420000011111111; -- assignment id
    ```
    Response:
    ```
    learner_activity_result_id |   lms_int_id    | lms_ext_id 
    ----------------------------+-----------------+------------
                    333333333 | 420000011111111 | 2222222
    ```
4. Now view the `posted_at` field ([in the way that it is queried here by MyLA](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron_udp.hjson#L236)):
    ```sql
    SELECT 
        learner_activity_result_id,
        posted_at,
        posted_at AT TIME ZONE 'America/Detroit' AS "posted_at (grade_posted_local_date)"
    FROM entity.learner_activity_result
    WHERE learner_activity_result_id = 333333333;
    ```
    This shows the wrong time being calculated (`grade_posted_local_date` in the MyLA query):
    ```
     learner_activity_result_id |        posted_at        | posted_at (grade_posted_local_date)        
    ----------------------------+-------------------------+------------------------------------
                      333333333 | 2021-10-17 16:49:11.908 |          2021-10-17 20:49:11.908+00
    ```

The `context_store`'s timestamps are in UTC.
```sql
show timezone;
 TimeZone 
----------
 UTC
```

The `America/Detroit` (or `EST`) timezone is 5 hours _behind_ UTC, not the 4 hours head that is returned by the queries:
```sql
select * from pg_timezone_names where name = 'America/Detroit';
      name       | abbrev | utc_offset | is_dst 
-----------------+--------+------------+--------
 America/Detroit | EST    | -05:00:00  | f
```
```sql
SELECT CURRENT_TIME AT TIME ZONE 'UTC', CURRENT_TIME AT TIME ZONE 'EST', CURRENT_TIME AT TIME ZONE 'America/Detroit';
      timezone      |      timezone      |      timezone      
--------------------+--------------------+--------------------
 21:58:56.198633+00 | 16:58:56.198633-05 | 16:58:56.198633-05
```
`grade_posted_local_date` should return `2021-10-17 11:49:11.908+00`.
- It was also noticed that converting the time with the timezone's name (`America/Detroit`) the incorrect time was still being computed. It was returning a time of only 4 hours behind instead of the correct 5 hours behind.
- Switching to using the timezone's abbreviation instead does provide the correct value.

The following contains multiple ways the queries can be corrected to return to correct timestamp:
```sql
SELECT 
    posted_at,
    posted_at AT TIME ZONE 'America/Detroit' AS "posted_at (original)",                           -- incorrect
    posted_at AT TIME ZONE 'UTC' AS "posted_at (UTC)",                                            -- shows time is unaffected by converting into UTC
    posted_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/Detroit' AS "posted_at (America/Detroit)", -- incorrect, original way
    posted_at AT TIME ZONE 'UTC' AT TIME ZONE 'EST' AS "posted_at (EST)",                         -- correct time
    posted_at::timestamp WITH TIME ZONE AT TIME ZONE 'EST' AS "posted_at (option 2)",             -- correct time
    posted_at::timestamptz AT TIME ZONE 'EST' AS "posted_at (option 3)"                           -- correct time
FROM entity.learner_activity_result
WHERE learner_activity_result_id = 333333333;
```
```
        posted_at        |    posted_at (original)    |      posted_at (UTC)       | posted_at (America/Detroit) |  posted_at (option 1)   |  posted_at (option 2)   |  posted_at (option 3)   
-------------------------+----------------------------+----------------------------+-----------------------------+-------------------------+-------------------------+-------------------------
 2021-10-17 16:49:11.908 | 2021-10-17 20:49:11.908+00 | 2021-10-17 16:49:11.908+00 | 2021-10-17 12:49:11.908     | 2021-10-17 11:49:11.908 | 2021-10-17 11:49:11.908 | 2021-10-17 11:49:11.908
```

### Additional context (Add any other context about the problem here) :

Affected queries:
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron.hjson#L41
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron.hjson#L116
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron_udp.hjson#L110
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron_udp.hjson#L236

### PR DESCRIPTION
**Pull request by jonespm**
Also Fixes #1432 - May need to make America/Detroit in cron config configurable

### CODE REVIEW

**Comment by jonespm** [comment]
@ssciolla I should have the time incorrect time zone issue that you noticed fixed now let me know! Looks like the column was just timezone and it needs to be explicit on what timezone the source is in. I missed that from the original examples.

**Review by ssciolla — APPROVED** [review]
Seems to be working with the latest changes. So we only need this extra syntax when we're using `timezone`? In other datetime fields, it's assumed to be UTC?

**Comment by jonespm** [comment]
I'm really not sure.

This column type is timestamp.
image

This *seems* like it won't have timezone information attached from this document.
https://www.javatpoint.com/postgresql-timestamp

Querying it will return the exact value that was put into it. I think we'll have to verify that doing this is giving the correct time from what's in Canvas. I'll review that over again next week. 

On that article they recommend doing this too

`SELECT timezone('America/New_York','2016-06-01 00:00'::timestamptz); `

But this produces a different time.

**Comment by jonespm** [comment]
Okay, looking at the database and matching the text in the body and from Canvas I can confirm the posted_at date is in UTC.
body: time: 2023-03-18 21:52:17 +0000
posted_at: 2023-03-18 21:52:17.38

So these are UTC.

I think the better fix as suggested would be to store these locally "as-is" and do the conversion after but that's on #1490.

**Pull request merged**
