### PR TITLE
reverse scrolling direction for resource view

### LINKED ISSUE #913: reverse resource view scrolling direction
### Expected behavior

Resource view scrolling should follow same direction as page scrolling.

### Describe the bug

The action to scroll the resource view is currently the opposite of that to scroll the page.

### Steps to Reproduce

1. Try scrolling a long web page.
1. Try scrolling the resource view.
1. Notice the different action required.

### Environment:

* **OS**: macOS 10.14.5
* **Browser**: Google Chrome 80.0.3987.163
* **Scroll setting**: macOS "Trackpad" preference panel's "Scroll Direction: Natural" setting is enabled.

### PR DESCRIPTION
**Pull request by yuandrew**
This PR fixes #913 by changing multiplying the `dy` value by -1 in the `scroll` function when creating the chart in `createResourceAccessChart.js`.

### CODE REVIEW

**Comment by lsloan** [comment]
Clever.  I'll try to make some time soon to test this change.

**Comment by jonespm** [comment]
When this is tested we should test it on Windows, and Mac both with scroll direction natural checked and unchecked. Also in Safari and at least one other browser.

I'd just wonder if we need to detect anything else in the Javascript.
https://stackoverflow.com/a/23668035/3708872

image

**Comment by pushyamig** [comment]
We have Browser Guideline list in wiki page https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/MyLA-Browser-Support

**Comment by lsloan** [comment]
Good point.  Wasn't asked about in the issue comments.  I'll add some info to the issue description.

**Comment by jonespm** [comment]
Yeah, I didn't think about it till I saw what the fix was! :) I know on Mac that's one of the first options I have to uncheck. So I wonder if it is different only for users that have that option checked. Didn't really consider it!

**Comment by lsloan** [comment]
I kinda like the fix you referred to on SO, @jonespm.  I was going to suggest to @yuandrew that a simple negative sign rather than the multiplication would suffice.  I didn't think of what it would do for people who use "unnatural" scrolling.  (Supernatural scrolling?  Freak of nature scrolling?)

If `event.webkitDirectionInvertedFromDevice` is usually available, I would use that to determine whether to negate the scrolling rather than the way the SO fix negates it, then conditionally negates it again (unnegating it).

**Comment by yuandrew** [comment]
I added a condition with `event.webkitDirectionInvertedFromDevice` to check scrolling direction and match the direction! I tested this on MacOS with Chrome, Safari, and Firefox, and they all seemed to work.

**Pull request merged**
