### PR TITLE
Fix #880 Current score line bug

### LINKED ISSUE #880: [Redesign assignment] Current score line bug
When the student doesn't have a current score, the current scoreline is a little bit off
Screen Shot 2020-01-29 at 2 11 39 PM

### PR DESCRIPTION
**Pull request by chrisrrowland**
labelPlacement 'downLower' will render lower when the line's value > 75
 this keeps text overwraping when word wrap occurs near the right margin
 probably wouldn't work well if max possible was really large like 400+

Adjusted zIndex so labels towards the top render above those below

### CODE REVIEW

**Comment by chrisrrowland** [comment]
image

0% progress

**Comment by chrisrrowland** [comment]
image

Max possible text shifted down when towards the right margin addresses word wrap
image

**Comment by pushyamig** [comment]
This is how I see it
1. when the `current score` is at zero the label should be towards the **right**, this case `Max possible` is further away from the `current score`
2. I think a measure of the distance between `current score` and `Max possible` should be know and based on that the current score label should be shifted. Otherwise, the overlapping will be confusing to the user. 
Thoughts??? @jennlove-um

**Comment by pushyamig** [comment]
@chrisrrowland You have opened a PR that is from you master, usually the practice we follow here is for every issue you work from forked branch Otherwise, if you wanted to work on a separate issue then the flow becomes a bit confusing

We follow Fork-branch based workflow, here is more info on it https://guides.github.com/activities/forking/ https://guides.github.com/introduction/flow/

In reality, you have 3 master branches, upstream master(Main TL Myla repo), forked master remote(your forked Myla repo), local myla repo( that you git cloned). The best practice is always to keep the forked repo( remote, local) in sync with upstream and don't commit any code to it. you only merge code to Main TL myla repo thru a PR from a branch

There are some tips here with [Git](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/CONTRIBUTING.md#tips-for-working-with-git)

**Comment by pushyamig** [comment]
@chrisrrowland Jest tests are written for the `Label` component and I just ran the Jest tests and I see a failing test

```
FAIL  assets/src/__tests__/components/Label.test.js
  ● renders correctly

    expect(received).toMatchSnapshot()

    Snapshot name: `renders correctly 1`

    - Snapshot
    + Received

    @@ -4,11 +4,11 @@
            "color": "blue",
            "display": "inline-block",
            "left": 5,
            "position": "absolute",
            "top": "-25px",
    -       "zIndex": 1,
    +       "zIndex": "3",
          }
        }
      >
        Hello world
      </div>

      16 |     ).toJSON()
      17 |
    > 18 |   expect(tree).toMatchSnapshot()
         |                ^
      19 | })
      20 |

      at Object.<anonymous> (assets/src/__tests__/components/Label.test.js:18:16)
```

I have a #945 PR open for fixing some of the Jest tests that are already failing. The main missing piece of the Jest from the master is a library called `react-test-renderer` is not added and that is the first point of the failure. You might not encounter a failure with the `Label` component unless that PR is merged.

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- assets/src/components/Label.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ITS_Teaching_And_Learning/my-learning-analytics/pullRequest?prid=5626610&bid=18431660)

**Comment by pushyamig** [comment]
@chrisrrowland My [PR](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/945) with fixing failing Jest test for assignment redesign is merged to master. You can pull in the latest from upstream master you can fix up the Jest test for the `Label` component now with your changes

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- assets/src/components/Label.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ITS_Teaching_And_Learning/my-learning-analytics/pullRequest?prid=5626610&bid=18431660)

**Pull request closed without merging**
