### PR TITLE
Add modified admin delete confirmation templates for course (#1067)

### PR DESCRIPTION
**Pull request by ssciolla**
This PR overrides portions of the `delete_confirmation.html` and `delete_selected_confirmation.html` templates for course objects so as to hide the extensive related-object information included by default. Summaries of what related objects will be deleted are still included. The PR aims to resolve issue #1067.

### CODE REVIEW

**Comment by ssciolla** [comment]
I couldn't find any ways to further limit the code copied verbatim here, since the most-specific block containing the things I needed to change is `content`. Let me know if you have any further ideas. Adding these template overrides seems somewhat risky for maintenance purposes, since any small change to the template language or the admin templates themselves could break this. I'm not sure how else to mitigate that.

**Comment by ssciolla** [comment]
@jonespm, any thoughts about this? I found a Django feature request about this problem (https://code.djangoproject.com/ticket/10919), and there were some suggestions about modifying the template context using method overrides, but that kind of thing might also be difficult to maintain and may also not solve the data marshaling problem (i.e. the data is still being queried for, which is probably the root cause of long-loading times). This PR "does the thing", but I think I'm still uncertain about whether the maintenance cost is worth the benefit.

**Review by jonespm — APPROVED** [review]
I think this looks like a good fix!

You're extending the template and just overriding the content. These files don't change much. Maybe in the future Django could break this into better organized blocks but this should be good and only require minor updates when we pick up major new releases of Django.

**Comment by jonespm** [comment]
I also tested this out locally and I think the summary looks better, Django should have this as an option by default. Amazed that issue was still open after 11 years.

**Comment by ssciolla** [comment]
Thanks, @jonespm! I fixed a spacing issue I saw, and I tweaked the language on the modified portion of the selected confirmation page for clarity. I'll merge shortly.

**Pull request merged**
