### PR TITLE
Fixes #1116 - Adding allcontributors support to MyLA

### LINKED ISSUE #1116: Add an contributor.md page to MyLA project
Thank you for contributing to this project!

### Describe your problem or feature you'd like added

Many people made contributions to the MyLA project: UX design, user testing, communications, evaluation, etc. We would like to recognize all our contributors.

### Describe the solution you'd like

I propose to use the ["All Contributors" Open Spec](https://allcontributors.org/docs/en/overview). We will have an authors.md page and can use the @all-contributors bot 🤖 to automate acknowledging contributors to MyLA project.

### PR DESCRIPTION
**Pull request by jonespm**
Example of the page
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/b0f0e79c59bebf0eac166c368429f9d90b310ff8/CONTRIBUTORS.md

Uses the [allcontributors.org](https://allcontributors.org/) spec.

### CODE REVIEW

**Comment by jonespm** [comment]
Let me know if I'm missing anyone or anyone has any comments on the format and style. I probably can add a page to the wiki for (us) about how to use this copied from the allcontributors page. I was going to add the bot so it could be done through Issues, but it can also be done through the CLI.

**Comment by pushyamig** [comment]
This Looks Great! I did not run this locally and neither I know if all contributors are included. I see all the people on the list whom I worked from before. 

The branch has a conflict to be resolved for merging.

**Review by zqian — COMMENTED** [review]
LGTM! I wonder whether the list can include the researcher names, even though they may not have a github account

**Comment by jonespm** [comment]
> LGTM! I wonder whether the list can include the researcher names, even though they may not have a github account

Looks like they've had that as an Issue since 2019. https://github.com/all-contributors/all-contributors/issues/339

Not sure how likely that is to get done with this spec. They'd probably have to be acknowledged somewhere else or with a different spec. I'm not sure if there's any frequently used format other than just a manual list. We could probably keep something like that in the Wiki and link to it.

**Comment by zqian** [comment]
`Looks like they've had that as an Issue since 2019. https://github.com/all-contributors/all-contributors/issues/339`

We can certainly wait till this feature is implemented. I will close the request and approve the PR.

**Pull request merged**
