### PR TITLE
Remove Django Debug Toolbar …

### LINKED ISSUE #1052: Remove django-debug-toolbar as it really doesn't do much for a React app
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Describe the bug (Tell us what happens instead of the expected behavior) :
Since we've switched to react, Django-Debug-Toolbar isn't providing as much information as it used to. There are no SQL calls or information captured by the SPA, only the initial page. 

There was a module and Chrome Extension [Django-Debug-Panel](https://github.com/recamshak/django-debug-panel) but it's been abandoned and not updated for 4 years.

### PR DESCRIPTION
**Pull request by jonespm**
Fixes #1052

Needs to be merged after #1073

### CODE REVIEW

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ITS_Teaching_And_Learning/my-learning-analytics/pullRequest?prid=6128728&bid=20046346)

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ITS_Teaching_And_Learning/my-learning-analytics/pullRequest?prid=6128728&bid=20046346)

**Comment by pushyamig** [comment]
This Change seems to be pretty straight forward. I don't see the tool bar anymore on UI. 
It's just the initial load time it give lot of option for profiling, DB etc. I find DB call timing useful when I was trying to debugging LTI launch. But that's when I figured the DB call are not culprit. But other than that I never used it.

It was only enabled for admins and why shouldn't we keep it for that case? what is the advantages for removing it?

**Comment by jonespm** [comment]
Reasons for removing:
1) It dumps a lot of warnings in the logs that we can't easily fix making the logs useless in the test instance
2) It doesn't work with React so the only value is on the first load of the template
3) It has a performance impact when using it as admin for various admin features, and it also overlaps other UI elements. 

It would make sense to leave in here if this project was 100% Django but loses a lot of value adding in another frontend framework.

**Comment by ssciolla** [comment]
> Reasons for removing:
> 
>     1. It dumps a lot of warnings in the logs that we can't easily fix making the logs useless in the test instance
> 
>     2. It doesn't work with React so the only value is on the first load of the template
> 
>     3. It has a performance impact when using it as admin for various admin features, and it also overlaps other UI elements.
> 
> 
> It would make sense to leave in here if this project was 100% Django but loses a lot of value adding in another frontend framework.

@pushyamig , I agree with everything @jonespm said here, particularly 1) and 3). Those template errors are super annoying, I think. This package has not been well maintained. Note that we aren't planning to ditch profiling tools forever; @jonespm already opened up issue #1071.

**Comment by ssciolla** [comment]
It does look like they are releasing a new major update: https://django-debug-toolbar.readthedocs.io/en/latest/changes.html#a4-2020-09-08

Maybe worth checking out later, but we'll need to consider @jonespm 's second point about the separate React FE.

**Comment by pushyamig** [comment]
ok, I am convinced. This can be merged.

**Review by pushyamig — APPROVED** [review]

**Review by ssciolla — APPROVED** [review]
Looks good to me! I did check the logs, and there is still a template related error, so must be some other problem there: `[base.py:867] Exception while resolving variable 'content' in template 'frontend/index.html'.` I'll look for and/or create a new issue.

**Comment by ssciolla** [comment]
Codacy has a couple minor issues flagged, one of which wasn't introduced here.

**Comment by jonespm** [comment]
Yeah, even with that new version it doesn't look like it would support React any better. I agree that when we review #1071 we'll should have something that should work well for everything.

**Pull request merged**
