### PR TITLE
Switch from PTVSD to debugpy

### LINKED ISSUE #1128: Switch from PTVSD to debugpy
PTVSD is deprecated [according to their Github 
](https://github.com/microsoft/ptvsd#-%E1%B4%98%E1%B4%9B%E1%B4%A0s%E1%B4%85-%C9%AAs-%E1%B4%85%E1%B4%87%E1%B4%98%CA%80%E1%B4%87%E1%B4%84%E1%B4%80%E1%B4%9B%E1%B4%87%E1%B4%85-) and replaced with [debugpy](https://github.com/microsoft/debugpy/).

We should switch to that to ensure the debugging support continues. It looks like this will involve some slight code changes.

### PR DESCRIPTION
**Pull request by jonespm**
Fixes #1128

If you're using this you'll have to rename your settings from `PTVSD_*` to `DEBUGPY_*`

### CODE REVIEW

**Comment by jonespm** [comment]
This will conflict on #1127

**Comment by jonespm** [comment]
Not sure if this will improve the issues you were seeing on the other ticket, but this is still working the same for me with VSCode.

The advantage of this method is it switches to "[Debug Adapter Protoco](https://microsoft.github.io/debug-adapter-protocol/)l" which should be more standard and adaptable.

**Comment by pushyamig** [comment]
Tested with `MyLA Docker Django` and I can see it is stopping at the breakpoint nicely.
Tested with `MyLA Docker Cron` I don't see it is attaching with this command `docker exec -it student_dashboard /bin/bash -c "DEBUGPY_WAIT_FOR_ATTACH=True DEBUGPY_ENABLE=TRUE DEBUGPY_REMOTE_PORT=3000 ./manage_debugpy.py runcrons --force"`

Here is the error log

```
i~/src/itsProjects/my-learning-analytics (debugpy)$ docker exec -it student_dashboard /bin/bash -c "DEBUGPY_WAIT_FOR_ATTACH=True DEBUGPY_ENABLE=TRUE DEBUGPY_REMOTE_PORT=3000 ./manage_debugpy.py runcrons --force"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/api.py", line 117, in debug
    port.__index__()  # ensure it's int-like
AttributeError: 'str' object has no attribute '__index__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage_debugpy.py", line 14, in <module>
    check_and_enable_debugpy()
  File "/code/debug_utils/debugpy.py", line 21, in check_and_enable_debugpy
    debugpy.listen((DEBUGPY_ADDRESS, DEBUGPY_PORT))
  File "/usr/local/lib/python3.8/site-packages/debugpy/__init__.py", line 113, in listen
    return api.listen(address)
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/api.py", line 119, in debug
    raise ValueError("expected port or (host, port)")
ValueError: expected port or (host, port)
```

Am I missing something

**Comment by jonespm** [comment]
I didn't test the cron debug, I'll double check this, thanks!

**Comment by jonespm** [comment]
Okay, I updated it. You might need to use a different port than 3000 as 3000 is the default one. It looks like 3001 is the default in the CONTRIBUTING.

**Review by pushyamig — APPROVED** [review]
Looks Good

**Pull request merged**
