### PR TITLE
Fixed Outlier Binning Logic (#794)

### PR DESCRIPTION
**Pull request by vjcao**
This PR addresses #794.

This:
Screen Shot 2019-11-15 at 4 06 29 PM

Becomes this:
Screen Shot 2019-11-20 at 12 25 57 PM

And this:
Screen Shot 2019-11-15 at 4 17 08 PM
Becomes this:
Screen Shot 2019-11-20 at 12 26 17 PM

### CODE REVIEW

**Comment by jennlove-um** [comment]
Let's hold on this one until we can talk with the team.  We originally designed the viz to have a space between the outlier bin and the lowest grade gin to make it more readable.

**Comment by jonespm** [comment]
@jennlove-um @pushyamig Do you remember if we had any update on this issue?

**Comment by pushyamig** [comment]
If I remember this issue reported is how it is in design. But Vincent felt it was a bug so he has a fix for it. 
We are trying to hear from student interviews if they also see this as a problem as reported in this issue. we can close this PR or talk it out in our weekly meeting @jennlove-um What do you think?

**Comment by pushyamig** [comment]
This change has been incorporated #1404, hence closing this.

**Pull request closed without merging**
